Document: st2api
Title: Debian st2api Manual
Author: <insert document author here>
Abstract: This manual describes what st2api is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/st2api/st2api.sgml.gz

Format: postscript
Files: /usr/share/doc/st2api/st2api.ps.gz

Format: text
Files: /usr/share/doc/st2api/st2api.text.gz

Format: HTML
Index: /usr/share/doc/st2api/html/index.html
Files: /usr/share/doc/st2api/html/*.html
