version: 2
executorType: machine
stages:
  build:
    workDir: ~/st2-packages
    environment:
      - DISTROS: trusty xenial el6 el7 wheezy jessie
      - ST2_PACKAGES: st2 st2mistral
    steps:
      - type: checkout
      - type: shell
        name: Stop Default Services
        command: |
          sudo service postgresql stop
          sudo service mongod stop
          sudo service rabbitmq-server stop
      - type: shell
        name: Show Docker versions
        command: |
          docker --version
          docker-compose --version
      - type: shell
        name: Initialize Build Environment
        command: |
          .circle/buildenv_st2.sh
          .circle/buildenv_mistral.sh
      - type: shell
        name: Node Auto-discovery
        command: |
          export DISCOVERY_ALIAS="${DISCOVERY_TOKEN}-${CIRCLE_SHA1}-${CIRCLE_BUILD_NUM}"
          echo "export DISCOVERY_ALIAS=$DISCOVERY_ALIAS" >> .buildenv
          if [[ $CIRCLE_NODE_INDEX = 0 ]]; then
            curl -sI "https://tinyurl.com/create.php?alias=${DISCOVERY_ALIAS}&url=$(hostname -i)"
          fi
      - type: shell
        name: Node Auto-discovery Retreival
        command: |
          . ~/.buildenv
          curl -sI "https://tinyurl.com/$DISCOVERY_ALIAS" | sed -En 's/^Location: http:\/\/(.*)/\1/p'
      - type: shell
        name: Pull Images
        command: |
          . ~/.buildenv
          .circle/docker-compose.sh pull ${DISTRO}
      - type: shell
        name: Build Packages
        command: |
          . ~/.buildenv
          .circle/docker-compose.sh build ${DISTRO}
      - type: shell
        name: Test Packages
        command: |
          . ~/.buildenv
          .circle/docker-compose.sh test ${DISTRO}
      - type: shell
        name: Copy Packages
        command: |
          . ~/.buildenv
          rsync -rv /tmp/st2-packages/ node0:~/packages/${DISTRO}
      - type: artifacts-store
        path: ~/packages
        destination: packages
