services:
  jammy:
    image: quay.io/stackstorm/packagingrunner
    working_dir: /root/st2-packages
    volumes_from:
      - container:st2-packages-vol
    environment:
      - BUILDNODE=jammybuild
      - TESTNODE=jammytest
      - ST2_PACKAGES=st2
    links:
      - jammybuild
      - jammytest
      - rabbitmq
      - mongodb
      - redis

  el9:
    image: quay.io/stackstorm/packagingrunner
    working_dir: /root/st2-packages
    volumes_from:
      - container:st2-packages-vol
    environment:
      - BUILDNODE=rockylinux9build
      - TESTNODE=rockylinux9test
    links:
      - rockylinux9build
      - rockylinux9test
      - rabbitmq
      - mongodb
      - redis

  ## Package build nodes
  jammybuild:
    image: stackstorm/packagingbuild:jammy
    volumes_from:
      - container:st2-packages-vol

  rockylinux9build:
    image: stackstorm/packagingbuild:rockylinux9
    volumes_from:
      - container:st2-packages-vol

  ## Package testing nodes
  jammytest:
    image: stackstorm/packagingtest:jammy-systemd
    privileged: true
    cgroup: host
    volumes_from:
      - container:st2-packages-vol
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup

  rockylinux9test:
    image: stackstorm/packagingtest:rockylinux9-systemd
    privileged: true
    cgroup: host
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes_from:
      - container:st2-packages-vol
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup

  rabbitmq:
    image: rabbitmq:4.2-management
    privileged: true
    hostname: rabbit
    ports:
      - "15672:15672"  # managment plugin port
      - "5672:5672"

  mongodb:
    image: mongo:8.2
    ports:
      - "27017:27017"

  redis:
    image: redis:8.6
    ports:
      - "6379:6379"
