Document: st2auth
Title: Debian st2auth Manual
Author: <insert document author here>
Abstract: This manual describes what st2auth is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/st2auth/st2auth.sgml.gz

Format: postscript
Files: /usr/share/doc/st2auth/st2auth.ps.gz

Format: text
Files: /usr/share/doc/st2auth/st2auth.text.gz

Format: HTML
Index: /usr/share/doc/st2auth/html/index.html
Files: /usr/share/doc/st2auth/html/*.html
