Document: st2actions
Title: Debian st2actions Manual
Author: <insert document author here>
Abstract: This manual describes what st2actions is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/st2actions/st2actions.sgml.gz

Format: postscript
Files: /usr/share/doc/st2actions/st2actions.ps.gz

Format: text
Files: /usr/share/doc/st2actions/st2actions.text.gz

Format: HTML
Index: /usr/share/doc/st2actions/html/index.html
Files: /usr/share/doc/st2actions/html/*.html
