FROM debian:jessie

# Buildenv is special environment for generating debian packages. It provides:
#   - All needed pre-installed development packages
#   - SSH access for build executor.
#

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y upgrade
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install vim python-dev python \
        build-essential git ssh && apt-get clean

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
        devscripts debhelper dh-make && apt-get clean

# We use must fresh version >= 0.8 of dh-virtualenv, but jessie offers 0.7.
# So we build it from source.
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
        python-setuptools python-sphinx python-mock python-virtualenv && \
        apt-get clean && \
        git clone https://github.com/spotify/dh-virtualenv.git /tmp/dh-virtualenv && \
        cd /tmp/dh-virtualenv && \
        dpkg-buildpackage -b -uc -us && dpkg -i ../dh-virtualenv_*.deb && \
        rm -rf /tmp/dh-virtualenv*

# Install fresh pip and co
RUN curl https://bootstrap.pypa.io/get-pip.py | python; pip install --upgrade virtualenv

# Create remote busybee remote user
RUN SHD=/home/busybee/.ssh && adduser --disabled-password --gecos "" busybee && \
    mkdir $SHD && chown busybee.busybee $SHD && chmod 700 $SHD

RUN SHD=/home/busybee/.ssh && echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOyk9g9x9sayUcpmEBY17dEXiqO99/AyzNcDozYTl7GYwHVaGJ91WqRETCgAQFRoSAVcWSgjlU0BB+TL74aCeRPKMBtfSc6IhjBgIh7gZNge2/oRngfSjCRwhk7Xb2Eca/ZvWV7S7254aV/BFxdtqRUHfMuGzRNiQtQ2GYps2YD5QzVkRsKh2HRL5JOc5sJAIcT27F1ZGUhvgnktR01kBGc8nIzQRGZVmz84ZwUbeCWgln5fP3p0H6AwO9k975n9+0NdW22HXnRbqY+t4rd0UySJ2KzOfAWXv2LAnLpPirYxyw9qARBiTVXjiNoMQzhrvke3/59sSfjas5hyFqmojf busybee" >> $SHD/authorized_keys && \
    chown busybee.busybee $SHD/authorized_keys

# Strange fix, but it's needed
RUN mkdir /var/run/sshd

RUN echo 'hello world' > /test.file

# Run ssh daemon in foreground and wait for bees to connect.
CMD ["/usr/sbin/sshd", "-D"]
