Document: st2client
Title: Debian st2client Manual
Author: <insert document author here>
Abstract: This manual describes what st2client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/st2client/st2client.sgml.gz

Format: postscript
Files: /usr/share/doc/st2client/st2client.ps.gz

Format: text
Files: /usr/share/doc/st2client/st2client.text.gz

Format: HTML
Index: /usr/share/doc/st2client/html/index.html
Files: /usr/share/doc/st2client/html/*.html
