Document: st2reactor
Title: Debian st2reactor Manual
Author: <insert document author here>
Abstract: This manual describes what st2reactor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/st2reactor/st2reactor.sgml.gz

Format: postscript
Files: /usr/share/doc/st2reactor/st2reactor.ps.gz

Format: text
Files: /usr/share/doc/st2reactor/st2reactor.text.gz

Format: HTML
Index: /usr/share/doc/st2reactor/html/index.html
Files: /usr/share/doc/st2reactor/html/*.html
