FROM quay.io/stackstorm/st2packages-buildenv-debian

ENV ST2_URI=https://github.com/dennybaa/st2.git \
    ST2_REV=setuptools_packaging_improvements

RUN git clone --depth 1 -b $ST2_REV $ST2_URI /code

ADD entry-point.sh /root/entry-point.sh

VOLUME ["/sources", "/out"]

ENTRYPOINT ["/bin/bash", "/root/entry-point.sh"]
